insert into usuario (
                     id,
                     cadastrocrm,
                     cpf,
                     data_nascimento,
                     email,
                     especializacao,
                     estado_civil,
                     genero,
                     naturalidade,
                     nome_completo,
                     rg,
                     senha,
                     telefone)
values (DEFAULT,
        '123456',
        '27726734051',
        date '1967-05-01',
        'helena.bruna.assis@pss.adv.br',
        'clínico geral',
        'casado',
        'feminino',
        'Cariacica',
        'Helena Bruna Assis',
        '22.854.461-0',
        '12345678',
        '27999498916');

insert into usuario (
                     id,
                     cadastrocrm,
                     cpf,
                     data_nascimento,
                     email,
                     especializacao,
                     estado_civil,
                     genero,
                     naturalidade,
                     nome_completo,
                     rg,
                     senha,
                     telefone)
values (DEFAULT,
        '654321',
        '30682887897',
        date '1958-04-17',
        'eduardo.luiz.darocha@bol.br',
        'pediatria',
        'solteiro',
        'masculino',
        'Santo Antônio do Descoberto',
        'Eduardo Luiz da Rocha',
        '29.194.240-4',
        '87654321',
        '61989015432');
insert into paciente (
                     id,
                     alergias,
                     cuidados_especificos,
                     contato_emergencia,
                     convenio,
                     numero_carteira_convenio,
                     validade_carteira_convenio,
                     cpf,
                     data_nascimento,
                     email,
                     estado_civil,
                     genero,
                     naturalidade,
                     nome_completo,
                     rg,
                     telefone)
values (DEFAULT,
        'diclofenaco',
        'nenhum',
        'Lúcia (21) 9989-0909',
        'Unimed',
        '243546',
        date '2023-10-01',
        '4560284740',
        date '1967-05-01',
        'pedro.marcos.aragao@db4.com.br',
        'casado',
        'masculino',
        'Cariacica',
        'Pedro Marcos Luiz Aragão',
        '24.243.830-1',
        '27999498916');
insert into paciente (
    id,
    alergias,
    cuidados_especificos,
    contato_emergencia,
    convenio,
    numero_carteira_convenio,
    validade_carteira_convenio,
    cpf,
    data_nascimento,
    email,
    estado_civil,
    genero,
    naturalidade,
    nome_completo,
    rg,
    telefone)
values (DEFAULT,
        'paracetamol',
        'nenhum',
        'André (41) 9888-9090',
        'Amil',
        '243546',
        date '2025-12-05',
        '27726734051',
        date '1983-26-12',
        'jessicabeneditasantos@clubedorei.com.br',
        'solteiro',
        'feminino',
        'Magé',
        'Jéssica Benedita Santos',
        '22.854.461-0',
        '27999498916');